name: build

on:
  merge_group:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: install-nix
        uses: DeterminateSystems/nix-installer-action@v10

      - name: build-frontend
        run: |
          nix develop --command bash -c "cd frontend && wasm32-wasi-cabal update && exec ./build.sh --debuginfo --low-memory-unused --converge --gufa --flatten --rereloop -Oz"

      - name: upload-pages-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/dist
          retention-days: 90

      - name: deploy-pages
        uses: actions/deploy-pages@v4
